version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: homexcarx-postgres
    environment:
      POSTGRES_USER: homexcarx_user
      POSTGRES_PASSWORD: homexcarx_pass
      POSTGRES_DB: homexcarx_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: homexcarx-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@homexcarx.com
      PGADMIN_DEFAULT_PASSWORD: admin_pass
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: always

volumes:
  postgres_data:
